# Generated by Django 4.2.28 on 2026-02-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
